name: Build Android (APK Debug)

on:
  push:
    branches:
      - QA

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
            distribution: 'zulu'
            java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install app dependencies
        run: npm install

      - name: Build Ionic App
        run: npm run build

      # - name: Capacitor Add
      #   run: npx cap add android

      - name: Capacitor Copy
        run: npx cap copy

      - name: Capacitor Sync
        run: npx cap sync

      - name: Build APP bundle
        run: cd android && chmod +x gradlew && ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          retention-days: 30
